var reviews = [
  {
    food: 'american',
    name: 'Cheezboard',
    reviewer: 'Sarah Anderson',
    review: 'The best vegetarian pizza I have ever had.',
    rating: 5,
    address: '6571 Culver Dr, Irvine, CA 92612',
    phone: '949-567-8901',
    id: 'cheezboard',
  },
  {
    food: 'chinese',
    name: 'Great China',
    reviewer: 'John Doe',
    review: 'Delicious food, excellent service',
    rating: 5,
    address: '6571 Culver Dr, Irvine, CA 92612',
    phone: '949-567-8901',
    id: 'greatchina',
  },
  {
    food: 'seafood',
    name: 'Oh Oyster',
    reviewer: 'Jen Kim',
    review: 'I ordered the daily special, but the oysters were not fresh at all.',
    rating: 2,
    address: '6571 Culver Dr, Irvine, CA 92612',
    phone: '949-567-8901',
    id: 'seafood',
  },
  {
    food: 'italian',
    name: 'Siciliana',
    reviewer: 'Ken Peterson',
    review: 'I do not understand why people line up for this place. It was okay.',
    rating: 3,
    address: '6571 Culver Dr, Irvine, CA 92612',
    phone: '949-567-8901',
    id: 'italian',
  },
  {
    food: 'korean',
    name: 'Baekjung',
    reviewer: 'Remmy Smith',
    review: 'Korean BBQ. Sooo good. I definitely want to go back again.',
    rating: 4,
    address: '6571 Culver Dr, Irvine, CA 92612',
    phone: '949-567-8901',
    id: 'korean',
  },
  {
    food: 'japanese',
    name: 'Sushi Sushi',
    reviewer: 'Jim Miller',
    review: 'Very low quality. I would rather get sushi from Wholefoods.',
    rating: 1,
    address: '6571 Culver Dr, Irvine, CA 92612',
    phone: '949-567-8901',
    id: 'italian',
  },
  {
    food: 'mexican',
    name: 'Tacos o Burritos',
    reviewer: 'Tucker Venditozzi',
    review: 'My favorite burritos in town. They should put more meat in them, though.',
    rating: 5,
    address: '6571 Culver Dr, Irvine, CA 92612',
    phone: '949-567-8901',
    id: 'tacos',
  },
  {
    food: 'foodtruck',
    name: 'Grab N Go',
    reviewer: 'Fred Huang',
    review: 'You do not want to miss out when their truck is in your area. It is just amazing. Order the cuban or the rubenesque.',
    rating: 4,
    address: '6571 Culver Dr, Irvine, CA 92612',
    phone: '949-567-8901',
    id: 'truck',
  },
  {
    food: 'dessert',
    name: 'Matcha Heaven',
    reviewer: 'Pooja Shah',
    review: 'All their dessert is made with green tea. If you like matcha, this is your place for dessert.',
    rating: 4,
    address: '6571 Culver Dr, Irvine, CA 92612',
    phone: '949-567-8901',
    id: 'heaven',
  },
  {
    food: 'coffee',
    name: 'Coffee-to-go',
    reviewer: 'Bri Angotti',
    review: 'Never coming back to this coffeeshop. Dirty and rude service for very cheap quality coffee.',
    rating: 1,
    address: '6571 Culver Dr, Irvine, CA 92612',
    phone: '949-567-8901',
    id: 'cafe',
  },
]

var myElement = document.getElementById('cheezboard')
myElement.addEventListener('click', function view(items, area) {
  var item = document.createElement('p');
  item.textContent = reviews[0].reviewer + " said: " + reviews[0].review;
  var position = document.getElementsByClassName('area')[0];
  position.appendChild(item);
});
